#pragma once

#include <SPI.h>
#include <cstdint>

#define CONFIGURATION__MOBO_REV_3 0
#define CONFIGURATION__MOBO_REV_4 0
#define CONFIGURATION__MOBO_REV_5 1

#define CONFIGURATION__MUX_DELAY_MICROSECONDS 5

#define CONFIGURATION__POT_DEADZONE 5.f
#define CONFIGURATION__POT_READS 5
#define CONFIGURATION__MAX_MODULES 16

#define CONFIGURATION__LOGGER__JACK_EVENTS 1
#define CONFIGURATION__LOGGER__CONNECTIONS 1
#define CONFIGURATION__LOGGER__MODULE_FACTORY 1
#define CONFIGURATION__LOGGER__ANALOG_RAW 1
#define CONFIGURATION__LOGGER__ANALOG_SMOOTHED 1
#define CONFIGURATION__LOGGER__CONTROL_CHANGES 1

#define CONFIGURATION__BACKGROUND_COLOR ILI9341_BLACK

#define CONFIGURATION__SERIAL_ENABLED 0
#define CONFIGURATION__SDCARD_ENABLED 0
#define CONFIGURATION__USBHOST_ENABLED 0

#define TEST_MODE_ENABLED 1
#define CONFIGURATION__TRACE_TOUCH 1         // Draw red dots at touch points for debugging
#define CONFIGURATION__DEBUG_TOUCH_RAW 1     // Display raw touch coordinates for calibration